apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: mozafaq/spark-master-k8s:3.1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9011
            - containerPort: 9012
            - containerPort: 9013
          resources:
            limits:
              memory: 512Mi
              cpu: 1000m
            requests:
              memory: 2Gi
              cpu: 1500m
          env:
            - name: AWS_ACCESS_KEY
              value: "<SECRET>"
            - name: AWS_SECRET_KEY
              value: "<SECRET>"
