apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker-instance
  labels:
    component: spark-worker

spec:
  replicas: 3
  selector:
    matchLabels:
      component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: mozafaq/spark-worker-k8s:3.1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9021
        resources:
          limits:
            memory: 512Mi
            cpu: 1000m
          requests:
            memory: 2Gi
            cpu: 1500m
        env:
          - name: AWS_ACCESS_KEY
            value: "<GET from SECRET>"
          - name: AWS_SECRET_KEY
            value: "<GET from SECRET>"
