/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package afaque.spring.boot.k8;

public class Application {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new Application().getGreeting());
    }
}
