apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-task-server-node
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-task-server
  template:
    metadata:
      labels:
        component: spark-task-server
    spec:
      containers:
        - name: spark-task-server
          image: mozafaq/spark-task-server:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9013
---
apiVersion: v1
kind: Service
metadata:
  name: spark-task-server-ip

spec:
  type: ClusterIP
  ports:
    - port: 9113
      targetPort: 9013
      name: spark-task-server
  selector:
    component: spark-task-server
