apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-pod-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: client-pod-deployment
        image: mozafaq/test-springboot-app:1.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /status
            port: 8081
          initialDelaySeconds: 30
          timeoutSeconds: 1

