apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: gateway-cluster-ip-service
              servicePort: 9011
          - path: /controller/
            backend:
              serviceName: worker-controller-cluster-ip-service
              servicePort: 9031



