kind: Service
apiVersion: v1
metadata:
  name: spark-master-headless
spec:
  ports:
  clusterIP: None
  selector:
    component: spark-master
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-server

spec:
  type: ClusterIP
  ports:
    - port: 9011
      targetPort: 9011
  selector:
    component: spark-master


