apiVersion: v1
kind: Service
metadata:
  name: worker-controller-cluster-ip-service

spec:
  type: ClusterIP
  ports:
    - port: 9031
      targetPort: 9031
  selector:
    component: worker-controller
